// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sia-modern/BoldColorful.tsx": () => import("../components/mockups/sia-modern/BoldColorful.tsx"),
  "./components/mockups/sia-modern/CleanModern.tsx": () => import("../components/mockups/sia-modern/CleanModern.tsx"),
  "./components/mockups/sia-modern/DarkElegant.tsx": () => import("../components/mockups/sia-modern/DarkElegant.tsx")
};
